home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomePageView.as_view(), name="log_home"),
    url(r'^logout/$', views.logout, name="logout"),
]

pots/urls.py
from django.conf.urls import url
from pots import views

app_name = 'pots'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^newpot/$', views.create_new_pot, name='newpot'),
]

smartcropadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from smartcropadmin.settings import ADMIN_ENABLED

urlpatterns = [
    url(r'^page/', include('home.urls')),
    url(r'^page/users/', include('users.urls')),
    url(r'^page/pots/', include('pots.urls')),
    url(r'^page/plants/', include('plants.urls')),
    url(r'^page/posts/', include('posts.urls')),
]

if ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

pots/forms.py
from django import forms


class EditPotForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    name = forms.CharField()
    owner = forms.CharField()

pots/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from auth.auth import log_required
from client.gets import get_all_pots, get_user
from client.puts import update_pot_owner, update_pot_name
from client.posts import new_pot
from pots.forms import EditPotForm


def create_new_pot(request):
    new_pot()
    return redirect("pots:index")


class IndexView(TemplateView):

    template_name = 'pots/pots_index.html'

    @log_required
    def get(self, request, *args, **kwargs):
        pots_list = []
        form = EditPotForm()
        for pot in get_all_pots()[1]:
            owner = 'Nadie'
            if 'owner' in pot:
                owner = pot['owner']
            pots_list.append({
                'id': pot['_id'],
                'name': pot['name'],
                'owner': owner,
                'requests': len(pot['requests']),
                'watchers': len(pot['watchers']),
            })
        return render(request, self.template_name, {'pots': pots_list, 'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditPotForm(request.POST)
        if form.is_valid():
            pot_id = form.cleaned_data['id']
            update_pot_name(pot_id, form.cleaned_data['name'])
            owner = form.cleaned_data['owner']
            status, _ = get_user(owner)
            if status == 200:
                update_pot_owner(pot_id, owner)

        return redirect('pots:index')

pots/templates/pots/pots_container.html
{% extends 'container.html' %}

{% block btn_extra %}
<a href="{% url 'pots:newpot' %}">
    <button class="btn btn-default navbar-btn">Añadir macetero</button>
</a>
{% endblock %}

pots/templates/pots/pots_index.html
{% extends 'pots/pots_container.html' %}
{% load form_style %}

{% block container %}

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'pots:index' %}" method="post">
                        {% csrf_token %}
                        {{form.id}}
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class="bmd-label-floating">Nombre</label>
                            {{ form.name|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.owner.id_for_label }}" class="bmd-label-floating">Dueño</label>
                            {{ form.owner|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Dueño</th>
                    <th>Solicitudes</th>
                    <th>Observadores</th>
                </tr>
            </thead>
            <tbody>
            {% for pot in pots %}
            <tr>
                <td>
                    <button data-toggle="tooltip" title="Copiar ID al portapapeles" class="btn btn-default nope"
                            id="button{{ forloop.counter0 }}" value="{{pot.id}}">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                </td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ pot.name }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ pot.owner }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ pot.requests }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ pot.watchers }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}
{% block jcode%}

    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });

    {% for pot in pots %}
        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ pot|dict_get:'name' }}");
            $('#{{ form.id.id_for_label }}').val("{{ pot|dict_get:'id' }}");
            $('#{{ form.name.id_for_label }}').val("{{ pot|dict_get:'name' }}");
            $('#{{ form.owner.id_for_label }}').val("{{ pot|dict_get:'owner' }}");
        });

        $("#button{{ forloop.counter0 }}").click(function() {
            var aux = document.createElement("input");
            aux.setAttribute("value", $("#button{{ forloop.counter0 }}").val());
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");

            document.body.removeChild(aux);
        });
    {% endfor %}


{% endblock %}