home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomePageView.as_view(), name="log_home"),
    url(r'^logout/$', views.logout, name="logout"),
]

smartcropadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from smartcropadmin.settings import ADMIN_ENABLED

urlpatterns = [
    url(r'^page/', include('home.urls')),
    url(r'^page/users/', include('users.urls')),
    url(r'^page/pots/', include('pots.urls')),
    url(r'^page/plants/', include('plants.urls')),
    url(r'^page/posts/', include('posts.urls')),
]

if ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

users/urls.py
from django.conf.urls import url
from users import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new/$', views.NewUserView.as_view(), name='new_user'),
]

users/forms.py
from django import forms


class EditUserForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    password = forms.CharField(required=False)
    name = forms.CharField()
    nickname = forms.CharField()
    avatar = forms.FileField(required=False)


class NewUserForm(forms.Form):
    name = forms.CharField()
    nickname = forms.CharField()
    mail = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(NewUserForm, self).clean()
        password = cleaned_data.get("password1")
        confirm_password = cleaned_data.get("password2")

        if password != confirm_password:
            self.add_error('password1', "Las contraseñas no coinciden")


class SearchForm(forms.Form):
    text = forms.CharField()

users/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from client.gets import search_user
from client.puts import update_user_nick, update_user_name, update_user_pass, update_profile
from client.posts import new_user_acc
from users.forms import EditUserForm, NewUserForm
from django.http import HttpResponseRedirect
from django.core.signing import Signer, BadSignature
from auth.auth import log_required
import os
import time


class IndexView(TemplateView):
    @log_required
    def get(self, request, *args, **kwargs):
        signer = Signer()
        users = []
        list_users = []
        user_search = request.GET.get("search-param")
        if user_search is not None:
            _, users = search_user(user_search)

        for user in users:
            data = {
                'id': signer.sign(user['_id']),
                'ID': user['_id'],
                'mail': user['email'],
                'name': user['name'],
                'nickname': user['nickname'],
                'avatar': user['avatar'],
            }

            list_users.append(data)
        form = EditUserForm()
        return render(request, "users/index.html", {'users': list_users, 'form': form})

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditUserForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                signer = Signer()
                user_id = signer.unsign(form.cleaned_data['id'])
                update_user_nick(user_id, form.cleaned_data['nickname'])
                update_user_name(user_id, form.cleaned_data['name'])
                update_user_pass(user_id, form.cleaned_data['password'])
                if len(request.FILES) > 0:
                    _, extension = os.path.splitext(request.FILES['avatar'].name)
                    path_file = 'media/'+str(int(time.time()))+extension
                    with open(path_file, 'wb+') as destination:
                        for chunk in request.FILES['avatar'].chunks():
                            destination.write(chunk)
                        update_profile(user_id, path_file)

                next_page = request.POST.get('next', '/')
                return HttpResponseRedirect(next_page)

            except BadSignature:
                pass

        return redirect("users:index")


class NewUserView(TemplateView):
    @log_required
    def get(self, request, *args, **kwargs):
        form = NewUserForm()
        return render(request, "users/userform.html", {'form': form})

    @log_required
    def post(self, request, *args, **kwargs):
        error = ""
        form = NewUserForm(request.POST)
        if form.is_valid():
            status = new_user_acc(form.cleaned_data['mail'],
                         form.cleaned_data['name'],
                         form.cleaned_data['password1'],
                         form.cleaned_data['nickname'])
            if status == 201:
                return redirect("users:index")
            else:
                error = 'Intentalo nuevamente'

        return render(request, "users/userform.html", {'form': form, 'error': error, })

users/templates/users/container.html
{% extends 'container.html' %}

{% block btn_extra %}
<a href="{% url 'users:new_user' %}">
    <button class="btn btn-default navbar-btn">Crear usuario</button>
</a>
{% endblock %}

{% block extra %}
    <form class="navbar-form" action="{% url 'users:index' %}" method="get">
        <div class="input-group">
            <input type="text" name="search-param" class="form-control" placeholder="Usuario">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
            </button>
            </div>
        </div>
    </form>

{% endblock %}

users/templates/users/index.html
{% extends 'users/container.html' %}
{% load form_style %}

{% block container %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
					<img id="image-profile-pic" src="" class="img-responsive">
                    <form action="{% url 'users:index' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.id}}
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class="bmd-label-floating">Nombre</label>
                            {{ form.name|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.nickname.id_for_label }}" class="bmd-label-floating">Cuenta</label>
                            {{ form.nickname|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.avatar.id_for_label }}" class="bmd-label-floating">Avatar</label>
                            {{ form.avatar|add_css:'form-control' }}
                        </div>
                        {% comment %}
                        <div class="form-group">
                            <label for="{{ form.password.id_for_label }}" class="bmd-label-floating">Contraseña nueva</label>
                            {{ form.password|add_css:'form-control' }}
                        </div>
                        {% endcomment %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Correo</th>
                    <th>Nombre</th>
                    <th>Cuenta</th>
                    <th>Avatar</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <button data-toggle="tooltip" title="Copiar ID al portapapeles" class="btn btn-default nope"
                            id="button{{ forloop.counter0 }}" value="{{user.ID}}">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                </td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ user.mail }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ user.name }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ user.nickname }}</td>
                <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ user.avatar }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block jcode%}

    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });

    {% for user in users %}
        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ user|dict_get:'mail' }}");
			$('#image-profile-pic').attr("src", "http://smartcrop.lightup.cl/uploads/{{ user|dict_get:'avatar' }}");
            $('#{{ form.id.id_for_label }}').val("{{ user|dict_get:'id' }}");
            $('#{{ form.name.id_for_label }}').val("{{ user|dict_get:'name' }}");
            $('#{{ form.nickname.id_for_label }}').val("{{ user|dict_get:'nickname' }}");
        });

        $("#button{{ forloop.counter0 }}").click(function() {
            var aux = document.createElement("input");
            aux.setAttribute("value", $("#button{{ forloop.counter0 }}").val());
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");

            document.body.removeChild(aux);
        });
    {% endfor %}

{% endblock %}

users/templates/users/userform.html
{% extends 'users/container.html' %}
{% load form_style %}

{% block container %}

<form action="{% url 'users:new_user' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p class="text-danger">{{error}}</p>
    <div class="form-group">
        {{form.name.errors}}
        <label for="{{ form.name.id_for_label }}" class="bmd-label-floating">Nombre</label>
        {{ form.name|add_css:'form-control' }}
    </div>
    <div class="form-group">
        {{form.nickname.errors}}
        <label for="{{ form.nickname.id_for_label }}" class="bmd-label-floating">Cuenta</label>
        {{ form.nickname|add_css:'form-control' }}
    </div>
    <div class="form-group">
        {{form.mail.errors}}
        <label for="{{ form.mail.id_for_label }}" class="bmd-label-floating">Correo electrónico</label>
        {{ form.mail|add_css:'form-control' }}
    </div>
    <div class="form-group">
        {{form.password1.errors}}
        <label for="{{ form.password1.id_for_label }}" class="bmd-label-floating">Contraseña</label>
        {{ form.password1|add_css:'form-control' }}
    </div>
    <div class="form-group">
        {{form.password2.errors}}
        <label for="{{ form.password2.id_for_label }}" class="bmd-label-floating">Repita contraseña</label>
        {{ form.password2|add_css:'form-control' }}
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block round">Crear cuenta</button>
    </div>
</form>

{% endblock %}