home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomePageView.as_view(), name="log_home"),
    url(r'^logout/$', views.logout, name="logout"),
]

plants/urls.py
from django.conf.urls import url
from plants import views

app_name = 'plants'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^newplant/$', views.create_new_plant, name='newplant'),
    url(r'^editplant/$', views.PlantInfoView.as_view(), name='editplant'),
]

smartcropadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from smartcropadmin.settings import ADMIN_ENABLED

urlpatterns = [
    url(r'^page/', include('home.urls')),
    url(r'^page/users/', include('users.urls')),
    url(r'^page/pots/', include('pots.urls')),
    url(r'^page/plants/', include('plants.urls')),
    url(r'^page/posts/', include('posts.urls')),
]

if ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

plants/models.py
from django.db import models

# Create your models here.

plants/forms.py
from django import forms
from client.gets import get_plant


class EditPlantForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    name = forms.CharField()

    minHumeTie = forms.IntegerField()
    maxHumeTie = forms.IntegerField()

    minHumeAmb = forms.IntegerField()
    maxHumeAmb = forms.IntegerField()

    minTempTie = forms.IntegerField()
    maxTempTie = forms.IntegerField()

    minTempAmb = forms.IntegerField()
    maxTempAmb = forms.IntegerField()


class InfoPlantForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.plant_id = None
        if 'plant_id' in kwargs:
            self.plant_id = kwargs.pop('plant_id')
        super(InfoPlantForm, self).__init__(*args, **kwargs)
        if self.plant_id is not None:
            status, plant = get_plant(self.plant_id)
            if status == 200:
                nombre = 'Sin nombre'
                desc = ''
                if 'description' in plant:
                    desc = plant['description']
                if 'name' in plant:
                    nombre = plant['name']
                self.fields['plant'] = forms.CharField(label='Planta',
                                                       disabled=True,
                                                       initial=nombre)
                self.fields['description'] = forms.CharField(label="Descripción",
                                                             widget=forms.Textarea(),
                                                             required=False,
                                                             initial=desc)
                self.fields['id'] = forms.CharField(widget=forms.HiddenInput(),
                                                    initial=plant['_id'])
                for tip in plant['tips']:
                    self.fields[tip['_id']+':type'] = forms.CharField(label='',
                                                                      initial=tip['type'],
                                                                      required=False)
                    self.fields[tip['_id']+':description'] = forms.CharField(label='',
                                                                             widget=forms.Textarea(),
                                                                             initial=tip['description'],
                                                                             required=False)

                self.fields['new_tip_type'] = forms.CharField(label='Titulo nuevo consejo',
                                                              required=False)
                self.fields['new_tip_description'] = forms.CharField(widget=forms.Textarea(),
                                                                     label='Descripción nuevo consejo',
                                                                     required=False)

    plant = forms.CharField()
    description = forms.CharField()

    def clean(self):
        cleaned_data = super(InfoPlantForm, self).clean()
        _new_type_type = cleaned_data.get("new_tip_type")
        _new_tip_description = cleaned_data.get("new_tip_description")
        key_list = list(cleaned_data.keys())
        new_type = cleaned_data.get("new_tip_type")
        if new_type in key_list:
            self.add_error('new_tip_type', "No puedes usar "+new_type+" como nuevo un nombre para un consejo.")

        if (len(_new_type_type) > 0) != (len(_new_tip_description) > 0):
            self.add_error('new_tip_type', "Para añadir un nuevo consejo se debe llenar el título y la descripción.")

plants/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from auth.auth import log_required
from client.posts import new_plant, new_plant_tip
from client.gets import get_all_plants
from client.deletes import delete_plant_tip
from client.puts import update_plant, update_plant_description, update_plant_category
from plants.forms import EditPlantForm, InfoPlantForm


def create_new_plant(request):
    new_plant()
    return redirect("plants:index")


class IndexView(TemplateView):

    template_name = 'plants/plants_index.html'

    @log_required
    def get(self, request, *args, **kwargs):
        plant_list = []
        form = EditPlantForm()
        for plant in get_all_plants()[1]:
            name = 'Sin nombre'
            if 'name' in plant:
                name = plant['name']
            plant_list.append({
                'id': plant['_id'],
                'name': name,
                'min_hume_tierra': plant['minMoist'],
                'max_hume_tierra': plant['maxMoist'],
                'min_temp_tierra': plant['minTemp'],
                'max_temp_tierra': plant['maxTemp'],
                'min_hume_amb': plant['minHum'],
                'max_hume_amb': plant['maxHum'],
                'min_temp_amb': plant['minRoomTemp'],
                'max_temp_amb': plant['maxRoomTemp'],
            })
        return render(request, self.template_name, {'plants': plant_list, 'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditPlantForm(request.POST)
        if form.is_valid():
            plant_id = form.cleaned_data['id']
            plant_name = form.cleaned_data['name']
            hume_tie = (form.cleaned_data['minHumeTie'], form.cleaned_data['maxHumeTie'])
            hume_amb = (form.cleaned_data['minHumeAmb'], form.cleaned_data['maxHumeAmb'])
            temp_tie = (form.cleaned_data['minTempTie'], form.cleaned_data['maxTempTie'])
            temp_amb = (form.cleaned_data['minTempAmb'], form.cleaned_data['maxTempAmb'])
            update_plant(plant_id, plant_name, hume_tie, hume_amb, temp_tie, temp_amb)

        return redirect('plants:index')


class PlantInfoView(TemplateView):

    template_name = 'plants/plants_edit_info.html'

    @log_required
    def get(self, request, *args, **kwargs):
        plant_id = request.GET.get("id")
        if plant_id is not None:
            form = InfoPlantForm(plant_id=plant_id)
            excluding_head_form = ['plant', 'description']
            excluding_foot_form = ['new_tip_type', 'new_tip_description']
            return render(request, self.template_name, {'form': form,
                                                        'excluding_foot_form': excluding_foot_form,
                                                        'excluding_head_form': excluding_head_form, })
        return redirect('plants:index')

    @log_required
    def post(self, request, *args, **kwargs):
        form = InfoPlantForm(request.POST, plant_id=request.POST['id'])
        if form.is_valid():
            plant_id = form.cleaned_data['id']
            description = form.cleaned_data['description']
            update_plant_description(plant_id, description)

            new_tip_type = form.cleaned_data['new_tip_type']
            new_tip_description = form.cleaned_data['new_tip_description']
            if len(new_tip_type) > 0:
                new_plant_tip(plant_id, new_tip_type, new_tip_description)

            all_entries = form.cleaned_data.copy()
            del all_entries['plant']
            del all_entries['id']
            del all_entries['description']
            del all_entries['new_tip_type']
            del all_entries['new_tip_description']

            for key in all_entries:
                key_split = key.split(':')
                if key_split[1] == 'type':
                    if len(all_entries[key]) > 0:
                        update_plant_category(plant_id,
                                              key_split[0],
                                              all_entries[key_split[0]+':type'],
                                              all_entries[key_split[0]+':description'])
                    else:
                        delete_plant_tip(plant_id, key_split[0])

            next_page = request.POST.get('next', '/')
            return HttpResponseRedirect(next_page)

        return render(request, self.template_name, {'form': form, })

plants/templates/plants/plants_container.html
{% extends 'container.html' %}

{% block btn_extra %}
<a href="{% url 'plants:newplant' %}">
    <button class="btn btn-default navbar-btn">Añadir especie de planta</button>
</a>
{% endblock %}

plants/templates/plants/plants_edit_info.html
{% extends 'container.html' %}
{% load form_style %}

{% block container %}

<form action="{% url 'plants:editplant' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.get_full_path }}">
    {{ form.id }}
    <div class="panel panel-default">
        <div class="panel-heading">
        {% for field in form.visible_fields %}
            {% if field.name in excluding_head_form %}
                {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
                <div class="form-group">
                {{ field|add_css:'form-control' }}
                </div>
            {% endif %}
        {% endfor %}
        </div>
        <div class="panel-body">
        {% for field in form.visible_fields %}
            {% if field.name not in excluding_head_form and field.name not in excluding_foot_form %}
                {% if forloop.counter0|divisibleby:2 %}
                <div class="well well-sm">
                    <div class="form-group">
                        {{ field|add_css:'form-control' }}
                    </div>
                {% else %}
                    <div class="form-group">
                        {{ field|add_css:'form-control' }}
                    </div>
                </div>
                {% endif %}
            {% endif %}
        {% endfor %}
        </div>
        <div class="panel-footer">
        {% for field in form.visible_fields %}
            {% if field.name in excluding_foot_form %}
                <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
                {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
                {{ field|add_css:'form-control' }}
            {% endif %}
        {% endfor %}
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
    </div>
</form>

{% endblock %}

plants/templates/plants/plants_index.html
{% extends 'plants/plants_container.html' %}
{% load form_style %}

{% block container %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'plants:index' %}" method="post">
                        {% csrf_token %}
                        {{ form.id }}
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class="bmd-label-floating">Nombre</label>
                            {{ form.name|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.minHumeTie.id_for_label }}" class="bmd-label-floating">Humedad de la tierra mínima</label>
                            {{ form.minHumeTie|add_css:'form-control' }}
                            <label for="{{ form.maxHumeTie.id_for_label }}" class="bmd-label-floating">Humedad de la tierra máxima</label>
                            {{ form.maxHumeTie|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.minHumeAmb.id_for_label }}" class="bmd-label-floating">Humedad ambiental mínima</label>
                            {{ form.minHumeAmb|add_css:'form-control' }}
                            <label for="{{ form.maxHumeAmb.id_for_label }}" class="bmd-label-floating">Humedad ambiental máxima</label>
                            {{ form.maxHumeAmb|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.minTempTie.id_for_label }}" class="bmd-label-floating">Temperatura de tierra mínima</label>
                            {{ form.minTempTie|add_css:'form-control' }}
                            <label for="{{ form.maxTempTie.id_for_label }}" class="bmd-label-floating">Temperatura de tierra máxima</label>
                            {{ form.maxTempTie|add_css:'form-control' }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.minTempAmb.id_for_label }}" class="bmd-label-floating">Temperatura ambiental mínima</label>
                            {{ form.minTempAmb|add_css:'form-control' }}
                            <label for="{{ form.maxTempAmb.id_for_label }}" class="bmd-label-floating">Temperatura ambiental máxima</label>
                            {{ form.maxTempAmb|add_css:'form-control' }}
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Humedad tierra</th>
                    <th>Humedad ambiental</th>
                    <th>Temperatura tierra</th>
                    <th>Temperatura ambiental</th>
                    <th>Información</th>
                </tr>
            </thead>
            <tbody>
                {% for plant in plants %}
                <tr>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ plant.name }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">Mín: {{ plant.min_hume_tierra }} Máx:{{ plant.max_hume_tierra }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">Mín: {{ plant.min_hume_amb }} Máx:{{ plant.max_hume_amb }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">Mín: {{ plant.min_temp_tierra }} Máx:{{ plant.max_temp_tierra }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">Mín: {{ plant.min_temp_amb }} Máx:{{ plant.max_temp_amb }}</td>
                    <td>
                        <form action="{% url 'plants:editplant' %}" method="get">
                            <button data-toggle="tooltip" title="Editar información general" class="btn btn-default nope"
                                id="button{{ forloop.counter0 }}" name="id" value="{{plant.id}}" type="submit">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block jcode%}

    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });

    {% for plant in plants %}
        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ plant|dict_get:'name' }}");
            $('#{{ form.id.id_for_label }}').val("{{ plant|dict_get:'id' }}");

            $('#{{ form.name.id_for_label }}').val("{{ plant|dict_get:'name' }}");

            $('#{{ form.minHumeTie.id_for_label }}').val("{{ plant|dict_get:'min_hume_tierra' }}");
            $('#{{ form.maxHumeTie.id_for_label }}').val("{{ plant|dict_get:'max_hume_tierra' }}");

            $('#{{ form.minHumeAmb.id_for_label }}').val("{{ plant|dict_get:'min_hume_amb' }}");
            $('#{{ form.maxHumeAmb.id_for_label }}').val("{{ plant|dict_get:'max_hume_amb' }}");

            $('#{{ form.minTempTie.id_for_label }}').val("{{ plant|dict_get:'min_temp_tierra' }}");
            $('#{{ form.maxTempTie.id_for_label }}').val("{{ plant|dict_get:'max_temp_tierra' }}");

            $('#{{ form.minTempAmb.id_for_label }}').val("{{ plant|dict_get:'min_temp_amb' }}");
            $('#{{ form.maxTempAmb.id_for_label }}').val("{{ plant|dict_get:'max_temp_amb' }}");

        });
    {% endfor %}

{% endblock %}