home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomePageView.as_view(), name="log_home"),
    url(r'^logout/$', views.logout, name="logout"),
]

posts/urls.py
from django.conf.urls import url
from posts import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^social/$', views.SocialView.as_view(), name='social'),
    url(r'^sales/$', views.SalesView.as_view(), name='sales'),
    url(r'^comments/$', views.CommentsView.as_view(), name='comments'),
    url(r'^new_comment/$', views.NewCommentsView.as_view(), name='new_comment'),
    url(r'^remove_comment/$', views.remove_comment, name='remove_comment'),
    url(r'^remove_post/$', views.remove_post, name='remove_post'),
    url(r'^remove_sale/$', views.remove_sale, name='remove_sale'),
    url(r'^new_social/$', views.NewSocialView.as_view(), name='new_social'),
    url(r'^new_sales/$', views.NewSalesView.as_view(), name='new_sales'),

]

smartcropadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from smartcropadmin.settings import ADMIN_ENABLED

urlpatterns = [
    url(r'^page/', include('home.urls')),
    url(r'^page/users/', include('users.urls')),
    url(r'^page/pots/', include('pots.urls')),
    url(r'^page/plants/', include('plants.urls')),
    url(r'^page/posts/', include('posts.urls')),
]

if ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

posts/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from client.gets import get_user
import re


class EditPostForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    photo = forms.FileField(label="Imagen", required=False)
    text = forms.CharField(label="Información extra", widget=forms.Textarea, required=True)


class NewPostForm(forms.Form):
    author = forms.CharField(label="ID del autor")
    image = forms.FileField(label="Imagen", required=False)
    text = forms.CharField(label="Información extra", widget=forms.Textarea, required=True)

    def clean_author(self):
        user_id = self.cleaned_data['author']
        status, _ = get_user(user_id)
        if status != 200:
            raise forms.ValidationError("No existe ese usuario")

        return user_id


class EditSaleForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    price = forms.IntegerField(label="Precio")
    image = forms.FileField(label="Imagen", required=False)
    text = forms.CharField(label="Información extra", widget=forms.Textarea)
    tags = forms.CharField(label="Etiquetas")

    def clean_price(self):
        price_positive = self.cleaned_data['price']
        if price_positive < 0:
            raise forms.ValidationError('El precio debe ser mayor a cero.')
        return price_positive

    def clean_tags(self):
        tags_format = self.cleaned_data['tags']
        regex = r"^\w(?:\w|\,\w)*$"
        matches = re.match(regex, tags_format.replace(" ", ""))
        if matches is None:
            raise forms.ValidationError('Las etiquetas deben estar de la forma "Etiqueta1, Etiqueta2, ..., EtiquetaN".')

        return tags_format


class NewSaleForm(forms.Form):
    author = forms.CharField(label="ID del autor")
    price = forms.IntegerField(label="Precio")
    image = forms.FileField(label="Imagen", required=False)
    text = forms.CharField(label="Información extra", widget=forms.Textarea)
    tags = forms.CharField(label="Etiquetas")

    def clean_author(self):
        user_id = self.cleaned_data['author']
        status, _ = get_user(user_id)
        if status != 200:
            raise forms.ValidationError("No existe ese usuario.")

        return user_id

    def clean_price(self):
        price_positive = self.cleaned_data['price']
        if price_positive < 0:
            raise forms.ValidationError('El precio debe ser mayor a cero.')
        return price_positive

    def clean_tags(self):
        tags_format = self.cleaned_data['tags']
        regex = r"^\w(?:\w|\,\w)*$"
        matches = re.match(regex, tags_format.replace(" ", ""))
        if matches is None:
            raise forms.ValidationError('Las etiquetas deben estar de la forma "Etiqueta1, Etiqueta2, ..., EtiquetaN".')

        return tags_format


class EditCommentForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    text = forms.CharField(label="Comentario", widget=forms.Textarea, required=True)


class NewCommentForm(forms.Form):
    author = forms.CharField(label="ID del autor")
    text = forms.CharField(label="Comentario", widget=forms.Textarea)

    def clean_author(self):
        user_id = self.cleaned_data['author']
        status, _ = get_user(user_id)
        if status != 200:
            raise forms.ValidationError("No existe ese usuario")

        return user_id

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from auth.auth import log_required
from client.gets import get_sales_posts, get_social_p, get_social_posts
from client.puts import update_post_image, update_post_text, update_comment, update_sale, update_sale_image
from client.posts import new_comment, new_post, new_post_image, new_sale, new_sale_image
from client.deletes import delete_comment, delete_post
from posts.forms import *
from django.http import HttpResponseRedirect
import os
import time


class IndexView(TemplateView):

    template_name = 'posts/posts_index.html'

    @log_required
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class SocialView(TemplateView):

    template_name = 'posts/posts_social.html'

    @log_required
    def get(self, request, *args, **kwargs):
        posts_list = []
        form = EditPostForm()
        for post in get_social_posts()[1]:
            imagen_default = "Sin imagen"
            if 'image' in post:
                imagen_default = post['image']
            posts_list.append({
                'post': post['_id'],
                'autor': post['author']['_id'],
                'autor_nick': post['author']['nickname'],
                'imagen': imagen_default,
                'cuerpo': post['text'],
            })
        return render(request, self.template_name, {'posts': posts_list, 'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditPostForm(request.POST, request.FILES)
        if form.is_valid():
            update_post_text(form.cleaned_data['id'], form.cleaned_data['text'])
            if len(request.FILES) > 0:
                _, extension = os.path.splitext(request.FILES['photo'].name)
                path_file = 'media/' + str(int(time.time())) + extension
                with open(path_file, 'wb+') as destination:
                    for chunk in request.FILES['photo'].chunks():
                        destination.write(chunk)
                    update_post_image(form.cleaned_data['id'], path_file)
        return redirect("posts:social")


class SalesView(TemplateView):

    template_name = 'posts/posts_sales.html'

    @log_required
    def get(self, request, *args, **kwargs):
        sales_list = []
        form = EditSaleForm()
        for sale in get_sales_posts()[1]:
            imagen_default = "Sin imagen"
            if 'image' in sale:
                imagen_default = sale['image']
            sales_list.append({
                'sale': sale['_id'],
                'author': sale['author']['_id'],
                'nick': sale['author']['nickname'],
                'price': sale['price'],
                'imagen': imagen_default,
                'cuerpo': sale['text'],
                'tags': ",".join(sale['tags']),
            })
        return render(request, self.template_name, {'sales': sales_list, 'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditSaleForm(request.POST, request.FILES)
        if form.is_valid():
            if len(request.FILES) > 0:
                _, extension = os.path.splitext(request.FILES['image'].name)
                path_file = 'media/' + str(int(time.time())) + extension
                with open(path_file, 'wb+') as destination:
                    for chunk in request.FILES['image'].chunks():
                        destination.write(chunk)
                    update_sale_image(form.cleaned_data['id'],
                                      form.cleaned_data['price'],
                                      path_file,
                                      form.cleaned_data['text'],
                                      form.cleaned_data['tags'])
            else:
                update_sale(form.cleaned_data['id'],
                            form.cleaned_data['price'],
                            form.cleaned_data['text'],
                            form.cleaned_data['tags'])
        return redirect("posts:sales")



class CommentsView(TemplateView):

    template_name = 'posts/posts_comments.html'

    @log_required
    def get(self, request, *args, **kwargs):
        post_search = request.GET.get("post_search")
        if post_search is not None:
            form = EditCommentForm()
            _, post = get_social_p(post_search)
            comments_list = []
            if "comments" in post:
                for comment in post['comments']:
                    comments_list.append({
                        'id': comment["_id"],
                        'autor': comment['author']['_id'],
                        'autor_name': comment['author']['nickname'],
                        'text': comment['text'],
                    })
            return render(request, self.template_name, {'post_id': post_search, 'comments': comments_list, 'form': form, })

        return redirect("posts:social")

    @log_required
    def post(self, request, *args, **kwargs):
        form = EditCommentForm(request.POST)
        if form.is_valid():
            print(request.POST.get("post_id"), form.cleaned_data['id'], form.cleaned_data['text'])
            update_comment(request.POST.get("post_id"), form.cleaned_data['id'], form.cleaned_data['text'])
            next_page = request.POST.get('next', '/')
            return HttpResponseRedirect(next_page)
        return redirect("posts:social")


class NewCommentsView(TemplateView):

    template_name = 'posts/posts_new_comment.html'

    @log_required
    def get(self, request, *args, **kwargs):
        post_search = request.GET.get("post_search")
        back = request.GET.get("back")
        if post_search is not None:
            form = NewCommentForm()
            return render(request, self.template_name, {'form': form, 'post_id': post_search, 'back': back, })

        return redirect("posts:social")

    @log_required
    def post(self, request, *args, **kwargs):
        form = NewCommentForm(request.POST)
        back = request.POST.get('back', '/')
        if form.is_valid():
            new_comment(request.POST.get('id'), form.cleaned_data['author'], form.cleaned_data['text'])
            return HttpResponseRedirect(back)
        else:
            return render(request, self.template_name, {'form': form, 'post_id': request.POST.get('id'), 'back': back, })
        return redirect("posts:social")


@log_required
def remove_comment(request):
    if request.method == "POST":
        delete_comment(request.POST.get("post_id"), request.POST.get("comment_id"))
        next_page = request.POST.get('next', '/')
        return HttpResponseRedirect(next_page)
    return redirect("posts:social")


@log_required
def remove_post(request):
    if request.method == "POST":
        delete_post(request.POST.get("post_id"))
    return redirect("posts:social")


@log_required
def remove_sale(request):
    if request.method == "POST":
        delete_post(request.POST.get("post_id"))
    return redirect("posts:sales")


class NewSocialView(TemplateView):

    template_name = 'posts/posts_new_social.html'

    @log_required
    def get(self, request, *args, **kwargs):
        form = NewPostForm()
        return render(request, self.template_name, {'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            if len(request.FILES) > 0:
                _, extension = os.path.splitext(request.FILES['image'].name)
                path_file = 'media/' + str(int(time.time())) + extension
                with open(path_file, 'wb+') as destination:
                    for chunk in request.FILES['image'].chunks():
                        destination.write(chunk)
                    new_post_image(form.cleaned_data['author'], path_file, form.cleaned_data['text'])
            else:
                new_post(form.cleaned_data['author'], form.cleaned_data['text'])
            return redirect("posts:social")
        return render(request, self.template_name, {'form': form, })


class NewSalesView(TemplateView):

    template_name = 'posts/posts_new_sales.html'

    @log_required
    def get(self, request, *args, **kwargs):
        form = NewSaleForm()
        return render(request, self.template_name, {'form': form, })

    @log_required
    def post(self, request, *args, **kwargs):
        form = NewSaleForm(request.POST, request.FILES)
        if form.is_valid():
            if len(request.FILES) > 0:
                _, extension = os.path.splitext(request.FILES['image'].name)
                path_file = 'media/' + str(int(time.time())) + extension
                with open(path_file, 'wb+') as destination:
                    for chunk in request.FILES['image'].chunks():
                        destination.write(chunk)
                    new_sale_image(form.cleaned_data['author'],
                                   form.cleaned_data['price'],
                                   path_file,
                                   form.cleaned_data['text'],
                                   form.cleaned_data['tags'])
            else:
                new_sale(form.cleaned_data['author'],
                         form.cleaned_data['price'],
                         form.cleaned_data['text'],
                         form.cleaned_data['tags'])
            return redirect("posts:sales")
        return render(request, self.template_name, {'form': form, })

posts/templates/posts/posts_comments.html
{% extends 'posts/posts_container.html' %}
{% load form_style %}

{% block container %}

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'posts:comments' %}" method="post">
                        {% csrf_token %}
                        {{form.id}}
                        <input type="hidden" name="post_id" value="{{ post_id }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
                            {% for error in field.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                            {{ field|add_css:'form-control' }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <form action="{% url 'posts:new_comment' %}" method="get">
        <input type="hidden" name="back" value="{{ request.get_full_path }}">
        <button type="submit" class="btn btn-default" name="post_search" value="{{ post_id }}">Nuevo comentario</button>
    </form>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID autor</th>
                    <th>Cuenta autor</th>
                    <th>Comentario</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for comment in comments %}
                <tr>
                    <td>
                        <button data-toggle="tooltip" title="Copiar ID al portapapeles" class="btn btn-default nope"
                            id="button{{ forloop.counter0 }}" value="{{comment.autor}}">
                            <span class="glyphicon glyphicon-copy"></span>
                        </button>
                    </td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ comment.autor_name }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ comment.text }}</td>
                    <td>
                        <form action="{% url 'posts:remove_comment' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.get_full_path }}">
                            <input type="hidden" name="post_id" value="{{ post_id }}">
                            <button data-toggle="tooltip" title="Eliminar comentario" class="btn btn-default nope"
                                type="submit" name="comment_id" value="{{ comment.id }}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block jcode%}
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    {% for comment in comments %}

        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ comment|dict_get:'autor_name' }}");
            $('#{{ form.id.id_for_label }}').val("{{ comment|dict_get:'id' }}");
            $('#{{ form.text.id_for_label }}').val("{{ comment|dict_get:'text' }}");
        });

        $("#button{{ forloop.counter0 }}").click(function() {
            var aux = document.createElement("input");
            aux.setAttribute("value", $("#button{{ forloop.counter0 }}").val());
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");

            document.body.removeChild(aux);
        });

    {% endfor %}
{% endblock %}

posts/templates/posts/posts_container_search.html
{% extends 'container.html' %}

{% block extra %}
    <form class="navbar-form" action="{% url 'posts:index' %}" method="get">
        <div class="input-group">
            <input type="text" name="search-param" class="form-control" placeholder="Etiquetas">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
            </button>
            </div>
        </div>
    </form>

{% endblock %}

posts/templates/posts/posts_new_comment.html
{% extends 'posts/posts_container.html' %}
{% load form_style %}

{% block container %}
<form action="{% url 'posts:new_comment' %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{ post_id }}" name="id">
    <input type="hidden" name="back" value="{{ back }}">
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
        {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
        {% endfor %}
        {{ field|add_css:'form-control' }}
    </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block round">Nuevo comentario</button>
    </div>
</form>
{% endblock %}

{% block jcode%}

{% endblock %}

posts/templates/posts/posts_new_sales.html
{% extends 'posts/posts_container.html' %}
{% load form_style %}

{% block container %}
<form action="{% url 'posts:new_sales' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
        {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
        {% endfor %}
        {{ field|add_css:'form-control' }}
    </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block round">Nueva venta</button>
    </div>
</form>
{% endblock %}

{% block jcode%}

{% endblock %}

posts/templates/posts/posts_sales.html
{% extends 'posts/posts_container.html' %}
{% load form_style %}

{% block container %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <img id="image" src="" class="img-responsive">
                    <form action="{% url 'posts:sales' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.id}}
                        {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
                            {% for error in field.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                            {{ field|add_css:'form-control' }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <a href="{% url 'posts:new_sales' %}">
        <button class="btn btn-default">Nueva venta</button>
    </a>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID autor</th>
                    <th>Cuenta autor</th>
                    <th>Precio</th>
                    <th>Imagen</th>
                    <th>Cuerpo</th>
                    <th>Etiquetas</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for sale in sales %}
                <tr>
                    <td>
                        <button data-toggle="tooltip" title="Copiar ID al portapapeles" class="btn btn-default nope"
                            id="button{{ forloop.counter0 }}" value="{{sale.author}}">
                            <span class="glyphicon glyphicon-copy"></span>
                        </button>
                    </td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ sale.nick }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ sale.price }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ sale.imagen }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ sale.cuerpo }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ sale.tags }}</td>
                    <td>
                        <form action="{% url 'posts:remove_sale' %}" method="post">
                            {% csrf_token %}
                            <button data-toggle="tooltip" title="Eliminar venta" class="btn btn-default nope"
                                type="submit" name="post_id" value="{{ sale.sale }}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block jcode%}
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    {% for sale in sales %}
        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ sale|dict_get:'nick' }}");
            $('#image').attr("src", "http://smartcrop.lightup.cl/uploads/{{ sale|dict_get:'imagen' }}");
            $('#{{ form.id.id_for_label }}').val("{{ sale|dict_get:'sale' }}");
            $('#{{ form.price.id_for_label }}').val("{{ sale|dict_get:'price' }}");
            $('#{{ form.text.id_for_label }}').val("{{ sale|dict_get:'cuerpo' }}");
            $('#{{ form.tags.id_for_label }}').val("{{ sale|dict_get:'tags' }}");
        });

        $("#button{{ forloop.counter0 }}").click(function() {
            var aux = document.createElement("input");
            aux.setAttribute("value", $("#button{{ forloop.counter0 }}").val());
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");

            document.body.removeChild(aux);
        });
    {% endfor %}
{% endblock %}

posts/templates/posts/posts_social.html
{% extends 'posts/posts_container.html' %}
{% load form_style %}

{% block container %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="title_modal">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <img id="image" src="" class="img-responsive">
                    <form action="{% url 'posts:social' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.id}}
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="{{ field.name }}" class="bmd-label-floating">{{ field.label }}</label>
                            {% for error in field.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                            {{ field|add_css:'form-control' }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block round">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <a href="{% url 'posts:new_social' %}">
        <button class="btn btn-default">Nueva publicación</button>
    </a>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID autor</th>
                    <th>Cuenta autor</th>
                    <th>Imagen</th>
                    <th>Cuerpo</th>
                    <th>Comentarios</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>
                        <button data-toggle="tooltip" title="Copiar ID al portapapeles" class="btn btn-default nope"
                            id="button{{ forloop.counter0 }}" value="{{post.autor}}">
                            <span class="glyphicon glyphicon-copy"></span>
                        </button>
                    </td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ post.autor_nick }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ post.imagen }}</td>
                    <td class="column{{ forloop.counter0 }}" data-toggle="modal" data-target="#myModal">{{ post.cuerpo }}</td>
                    <td>
                        <form action="{% url 'posts:comments' %}" method="get">
                            <button data-toggle="tooltip"
                                    title="Editar información general"
                                    class="btn btn-default nope"
                                    value="{{ post.post }}"
                                    name="post_search"
                                    type="submit">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'posts:remove_post' %}" method="post">
                            {% csrf_token %}
                            <button data-toggle="tooltip" title="Eliminar publicación" class="btn btn-default nope"
                                type="submit" name="post_id" value="{{ post.post }}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block jcode%}
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    {% for post in posts %}
        $(".column{{ forloop.counter0 }}").click(function() {
            $('#title_modal').html("{{ post|dict_get:'autor_nick' }}");
            $('#image').attr("src", "http://smartcrop.lightup.cl/uploads/{{ post|dict_get:'imagen' }}");
            $('#{{ form.id.id_for_label }}').val("{{ post|dict_get:'post' }}");
            $('#{{ form.text.id_for_label }}').val("{{ post|dict_get:'cuerpo' }}");
        });

        $("#button{{ forloop.counter0 }}").click(function() {
            var aux = document.createElement("input");
            aux.setAttribute("value", $("#button{{ forloop.counter0 }}").val());
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");

            document.body.removeChild(aux);
        });
    {% endfor %}
{% endblock %}